name: CI - Pruebas Unitarias

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17, 21]
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    
    - name: Cache dependencias Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Ejecutar pruebas
      run: mvn clean test
    
    - name: Generar reporte de cobertura
      run: mvn jacoco:report
      if: matrix.java-version == '17'
    
    - name: Subir reporte de cobertura a Codecov
      uses: codecov/codecov-action@v3
      if: matrix.java-version == '17'
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache dependencias Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Compilar proyecto
      run: mvn clean compile
    
    - name: Empaquetar aplicación
      run: mvn package -DskipTests
    
    - name: Guardar artefacto
      uses: actions/upload-artifact@v3
      with:
        name: calculadora-pedidos-jar
        path: target/*.jar
